Add/vnla 2734 initial commit
vanilla/keen-anonymizer pull request #1
Opened 2022-10-19 22:51 UTC by thundrax

Initial commit.

2022-10-24 20:12 UTC, blutarch requested changes
Just some very minor stuff.

2022-10-24 20:12 UTC, blutarch commented on .github/ranger.yml
> +labels:
I don't think we really need this, although it isn't doing any harm. Same for `stale.yml`

2022-10-24 20:12 UTC, blutarch commented on README.md
> +When user on the site is anonymized, their data should also be anonymized in keen analytics data.
```suggestion
When a user on the site is anonymized, their data should also be anonymized in the keen analytics data.
```

2022-10-24 20:12 UTC, blutarch commented on src/Anonymize.php
> +     * @param array $properties - properties to anonymize, and to what, format {"property_name": "quantity","property_value": 0 }
I think there's something grammatical amiss here. Or a missing word?

2022-10-24 21:23 UTC, charrondev requested changes
Could we encapsulate the HTTP client in the class?

I don't think we really want to be exposing all those other client methods.

Additionally maybe we could rename this to `Anonymizer`?

2022-10-24 21:23 UTC, charrondev commented on src/Anonymize.php
> +                                "property_type" => "Number",
We don't actually need to specify this.

2022-10-24 21:23 UTC, charrondev commented on tests/AnonymizeTest.php
> +            "startDate" => $startDate->format(DateTimeInterface::ISO8601),
```suggestion
            "startDate" => $startDate->format(DateTimeInterface::RFC3339),
```

We tend to user RFC3339 everywhere else.

2022-10-24 21:23 UTC, charrondev commented on .circleci/config.yml
> +      - image: "circleci/php:7.2.9-cli"
We can pretty safely just use 1 php 7.4 image here. No need to use any of the others.

Also we tend not to use phpcs anymore either, so that can pretty safely be dropped. If you want to add some syntax validation bring in prettier (like vanilla-cloud).

2022-10-24 21:23 UTC, charrondev commented on src/Anonymize.php
> +                        new Exception($response->getBody());
What exception are we expecting here? If we're using the exception throwing mode they will already be converted to exceptions.

2022-10-25 15:27 UTC, charrondev requested changes

2022-10-25 15:27 UTC, charrondev commented on src/Anonymizer.php
> +        $this->httpClient = new HttpClient();
You'll definitely want to make this dependency injected so that we can apply middlewares on it from the external app.

2022-10-26 14:48 UTC, charrondev approved these changes

2022-10-26 14:48 UTC, merged